clear;
close all;
clc;

% 1. To use CNN based classifier, set classifier = 1
% 2. To use SVM based classifier, set classifier = 2
classifier = 1;

% Accessing the root folder where the segmented characters are stored
root_directory = fullfile('Segmented_characters/');
segmented_data = imageDatastore(root_directory, "IncludeSubfolders", true, "LabelSource", "foldernames");

num_segmented_images = numel(segmented_data.Files);

% Displays the characters along with corresponding labels generated by the classifier

if classifier == 1
    figure;
    load CNN_Trained_Model.mat
    predictions = classify(CNN_Trained_Model_9932, segmented_data);
    for i = 1:num_segmented_images
        subplot(2, 5, i);
        imshow(segmented_data.Files{i});
        title(['Predicted:', char(predictions(i))]);
    end
elseif classifier == 2
    figure;
    load SVM_Trained_Model.mat
    for i =1:num_segmented_images
        subplot(2, 5, i);
        imshow(segmented_data.Files{i});
        img = readimage(segmented_data, i);
        [Features] = extractHOGFeatures(img, 'CellSize', [20 20]);
        predicted_label = predict(SVM_Trained_Model, Features);
        title(['Predicted:', char(predicted_label)]);
    end
end

